export const ABRIR_MODAL = "ABRIR_MODAL";
export const CERRAR_MODAL = "CERRAR_MODAL";

export const REGISTRAR_CLIENTE = "REGISTRAR_CLIENTE";
export const LISTAR_CLIENTE = "LISTAR_CLIENTE";
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE";
